---
## ---------------
## 全体の設定
## ---------------
# disabled:
#   # - js
#   # - css
#   - html
## ---------------
## HTML用の設定
## ---------------
html:
  srcDir: src
  outputDir: dist
  exts:
    - njk
    - twig
  ignore:
    filePrefix: _
    fileSuffix: -bk
    dirSuffix: -bk
    dirNames:
      - layout
      - element
## ---------------
## CSS用の設定
## ---------------
css:
  srcDir: src/scss
  outputDir: dist/assets/css
  exts:
    - scss
    - sass
    - css
  ignore:
    filePrefix: _
    fileSuffix: -bk
    dirSuffix: -bk
## ---------------
## JS用の設定
## ---------------
js:
  srcDir: src
  outputDir: dist/assets/js
  exts:
    - js
    - ts
  moduleExts:
    - mjs
    - mts
    - cjs
    - cts
  ignore:
    fileSuffix: -bk
    dirSuffix: -bk
    dirNames:
      - node_modules
      - vendor
      - lib
  # globals:
  #   jquery: $
