---
## ---------------
## ビルダーの有効化
## ---------------
enable:
  - js
  - css
  - html
## ---------------
## サーバーの設定
## ---------------
# server:
#   baseDir: public
#   port: 3000
#   watch: true
#   watchFiles: []
#   open: true
#   browser: default
#   notify: false
#   ui: false
#   uiPort: 3001
## ---------------
## 共通設定項目
## ---------------
# srcDir: src
# outputDir: public
# ignore:
#   filePrefix: null
#   fileSuffix: null
#   dirPrefix: null
#   dirSuffix: null
#   dirNames: []
# beautifyOption: {}
## ---------------
## HTMLのビルド設定
## ---------------
html:
#   srcDir: src
#   outputDir: public
  ignore:
    dirNames:
      - element
      - layout
## ---------------
## CSSのビルド設定
## ---------------
# css:
#   srcDir: src
#   outputDir: public/assets/css
#   exts:
#     - scss
#     - sass
#     - css
#   moduleExts: []
#   ignore:
#     filePrefix: _
#     fileSuffix: null
#     dirPrefix: null
#     dirSuffix: null
#     dirNames: []
#   compileOption: {}
#   beautifyOption: {}
#   style: null
#   generateIndex: false
#   indexFileName: _all.scss
#   indexImportType: forward
#   sourcemap: null
#   loadPaths:
#     - ${srcDir}
#     - node_modules
## ---------------
## JavaScriptのビルド設定
## ---------------
js:
  # outputDir: public/assets/js
  ignore:
    prefix: _
    dirNames:
      - node_modules
      - vendor
## ---------------
## スニペットのビルド設定
## ---------------
# snippet:
#   srcDir: docs/cheatsheet
#   snippetHeaderLevel: 2
#   extraSettingHeaderLevel: 3
#   extraSettingHeaderTexts:
#     - Snippet Setting
#     - Snippet Settings
#     - VSCode Extra Setting
#     - VSCode Extra Settings
#     - VSCode Snippet Setting
#     - VSCode Snippet Settings
## ---------------
## スクリーンショットの設定
## ---------------
screenshot:
  ## スクリーンショットの保存先ディレクトリ
  # outputDir: screenshots
  ## ディレクトリを作成せずにフラットにスクリーンショットを保存する
  # saveFlatPath: true
  ## デフォルトのブラウザ設定
  # default:
  #   type: chromium
  #   width: 1920
  #   height: 1080
  targets:
    desktop:
      type: Desktop Chrome
      width: 1920
      height: 1080
    mobile:
      type: iPhone 14 Pro
    # mobile_landscape:
    #   type: iPhone 14 Pro landscape
